### ISSUE TITLE
GUI overlaying and no padding on the border in add, search, edit and delete

### ISSUE THREAD

**Issue by WojciechSzade** [utilmen/ems#15]
Add employee (no padding on the right):
![image](https://user-images.githubusercontent.com/96198418/194407749-71d85101-4e4d-422c-856e-3eaf98ac927d.png)
 Search record (no padding and Find button overlaying:
 ![image](https://user-images.githubusercontent.com/96198418/194407892-1d3bdcba-90eb-4661-92e2-0ce072dd3734.png)
Edit record (no padding and Find button overlaying):
Same as search record before pressing find. After, pressing I would only move Find button to the left.
![image](https://user-images.githubusercontent.com/96198418/194408181-300afa47-c461-4aaa-b07d-667165ab12ce.png)
Delete record:
Same as search.
Also:
Quit button is to small (height):
![image](https://user-images.githubusercontent.com/96198418/194408397-83e164aa-0ff3-4cc4-83f0-988d6ac80d6c.png)
Every error is on Ubuntu 22.

**Comment by WojciechSzade** [comment]
Please assign this issue to me.

**Comment by binbard** [comment]
Perfect, assigned
